default_context:
  project_name: 'work 2.0'
  project_slug: 'work-2.0'
  domain_main: 'work-2.0.com'
  domain_staging: 'stag.work-2.0.com'
  docker_swarm_stack_name_main: 'work-2-0-com'
  docker_swarm_stack_name_staging: 'stag-work-2-0-com'
  secret_key: 'changethis'
  first_superuser: 'admin@work-2.0.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.work-2.0.com", "https://stag.work-2.0.com", "https://work-2.0.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@work-2.0.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@work-2.0.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'work-2.0.com'
  traefik_constraint_tag_staging: 'stag.work-2.0.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
