"""Add internal employee

Revision ID: 1fa08c74081d
Revises: a79f8b7682ea
Create Date: 2022-04-19 08:06:38.201752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa08c74081d'
down_revision = 'a79f8b7682ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal-employee', sa.Column('militaryServiceAttitudeId', sa.Integer(), nullable=True))
    op.add_column('internal-employee', sa.Column('ldapLoginId', sa.Integer(), nullable=True))
    op.drop_constraint('internal-employee_militaryServiceAttitudeID_fkey', 'internal-employee', type_='foreignkey')
    op.create_foreign_key(None, 'internal-employee', 'military-service-attitude', ['militaryServiceAttitudeId'], ['id'])
    op.create_foreign_key(None, 'internal-employee', 'ldap-login', ['ldapLoginId'], ['id'])
    op.drop_column('internal-employee', 'militaryServiceAttitudeID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal-employee', sa.Column('militaryServiceAttitudeID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'internal-employee', type_='foreignkey')
    op.drop_constraint(None, 'internal-employee', type_='foreignkey')
    op.create_foreign_key('internal-employee_militaryServiceAttitudeID_fkey', 'internal-employee', 'military-service-attitude', ['militaryServiceAttitudeID'], ['id'])
    op.drop_column('internal-employee', 'ldapLoginId')
    op.drop_column('internal-employee', 'militaryServiceAttitudeId')
    # ### end Alembic commands ###
