"""Edit appointment

Revision ID: 35345b17d92b
Revises: dc4a859a5201
Create Date: 2022-04-20 08:28:52.125582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35345b17d92b'
down_revision = 'dc4a859a5201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decreeId', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('isFRP', sa.Boolean(), nullable=True),
    sa.Column('isTemporary', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('employeeId', sa.Integer(), nullable=True),
    sa.Column('staffUnitId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['internal-employee.id'], ),
    sa.ForeignKeyConstraint(['staffUnitId'], ['staff-unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_id'), 'appointment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_id'), table_name='appointment')
    op.drop_table('appointment')
    # ### end Alembic commands ###
