"""Add position

Revision ID: 41aa8724944a
Revises: 46e0f6a27977
Create Date: 2022-04-18 12:17:33.906573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aa8724944a'
down_revision = '46e0f6a27977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('declinationId', sa.Integer(), nullable=True))
    op.drop_column('position', 'declination_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('declination_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('position', 'declinationId')
    # ### end Alembic commands ###
