"""Add nationality

Revision ID: 43282308ee49
Revises: 5ad1bf7f2ff9
Create Date: 2022-04-18 10:40:40.309963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43282308ee49'
down_revision = '5ad1bf7f2ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationality-sap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality-sap_id'), 'nationality-sap', ['id'], unique=False)
    op.create_table('nationality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('nationalitySAPId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nationalitySAPId'], ['nationality-sap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality_id'), 'nationality', ['id'], unique=False)
    op.create_table('nationality-gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('nationalityId', sa.Integer(), nullable=True),
    sa.Column('genderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genderId'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['nationalityId'], ['nationality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality-gender_id'), 'nationality-gender', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nationality-gender_id'), table_name='nationality-gender')
    op.drop_table('nationality-gender')
    op.drop_index(op.f('ix_nationality_id'), table_name='nationality')
    op.drop_table('nationality')
    op.drop_index(op.f('ix_nationality-sap_id'), table_name='nationality-sap')
    op.drop_table('nationality-sap')
    # ### end Alembic commands ###
