"""Edit appointment

Revision ID: 5209f48258e7
Revises: 35345b17d92b
Create Date: 2022-04-20 08:30:02.886806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5209f48258e7'
down_revision = '35345b17d92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
