"""Add employee status

Revision ID: 5ad1bf7f2ff9
Revises: ebaabd3e47ef
Create Date: 2022-04-18 10:10:43.979468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad1bf7f2ff9'
down_revision = 'ebaabd3e47ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee-status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee-status_id'), 'employee-status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee-status_id'), table_name='employee-status')
    op.drop_table('employee-status')
    # ### end Alembic commands ###
