"""add staff unit role

Revision ID: 695d6a3b8fe9
Revises: 41aa8724944a
Create Date: 2022-04-19 06:29:22.681508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695d6a3b8fe9'
down_revision = '41aa8724944a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff-unit-role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employeeFuncRoleSpecId', sa.Integer(), nullable=True),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff-unit-role_id'), 'staff-unit-role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff-unit-role_id'), table_name='staff-unit-role')
    op.drop_table('staff-unit-role')
    # ### end Alembic commands ###
