"""Add staff_unit_type

Revision ID: 888e7fb40601
Revises: cda7589945b4
Create Date: 2022-04-18 09:48:21.385337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888e7fb40601'
down_revision = 'cda7589945b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff-unit-type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff-unit-type_id'), 'staff-unit-type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff-unit-type_id'), table_name='staff-unit-type')
    op.drop_table('staff-unit-type')
    # ### end Alembic commands ###
