"""Add marital

Revision ID: 9e6b1f699dee
Revises: 95b98a4a2032
Create Date: 2022-04-18 11:50:46.819698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6b1f699dee'
down_revision = '95b98a4a2032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nationality-gender', 'isActive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nationality-gender', sa.Column('isActive', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
