"""Add internal employee

Revision ID: a540d5b9b71b
Revises: 1fa08c74081d
Create Date: 2022-04-19 08:14:44.215550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a540d5b9b71b'
down_revision = '1fa08c74081d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
