"""Add internal employee

Revision ID: a79f8b7682ea
Revises: 8f3ab208fb30
Create Date: 2022-04-19 07:53:39.539876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79f8b7682ea'
down_revision = '8f3ab208fb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marital-status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('genderId', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genderId'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marital-status_id'), 'marital-status', ['id'], unique=False)
    op.create_table('internal-employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individualId', sa.Integer(), nullable=True),
    sa.Column('legalOrganizationlId', sa.Integer(), nullable=True),
    sa.Column('fullnameDeclinationId', sa.Integer(), nullable=True),
    sa.Column('financialAccountId', sa.Integer(), nullable=True),
    sa.Column('iin', sa.String(), nullable=True),
    sa.Column('personnelNumber', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('middleName', sa.String(), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('workStartDate', sa.Date(), nullable=True),
    sa.Column('isReserveMember', sa.Boolean(), nullable=True),
    sa.Column('isInsider', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('statusId', sa.Integer(), nullable=True),
    sa.Column('gradeId', sa.Integer(), nullable=True),
    sa.Column('maritalStatusId', sa.Integer(), nullable=True),
    sa.Column('militaryServiceAttitudeID', sa.Integer(), nullable=True),
    sa.Column('nationalityGenderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gradeId'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['maritalStatusId'], ['marital-status.id'], ),
    sa.ForeignKeyConstraint(['militaryServiceAttitudeID'], ['military-service-attitude.id'], ),
    sa.ForeignKeyConstraint(['nationalityGenderId'], ['nationality-gender.id'], ),
    sa.ForeignKeyConstraint(['statusId'], ['employee-status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal-employee_id'), 'internal-employee', ['id'], unique=False)
    op.drop_index('ix_marital_status_id', table_name='marital_status')
    op.drop_table('marital_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marital_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nameRu', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nameKz', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genderId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genderId'], ['gender.id'], name='marital_status_genderId_fkey'),
    sa.PrimaryKeyConstraint('id', name='marital_status_pkey')
    )
    op.create_index('ix_marital_status_id', 'marital_status', ['id'], unique=False)
    op.drop_index(op.f('ix_internal-employee_id'), table_name='internal-employee')
    op.drop_table('internal-employee')
    op.drop_index(op.f('ix_marital-status_id'), table_name='marital-status')
    op.drop_table('marital-status')
    # ### end Alembic commands ###
