"""add Staff Unit

Revision ID: b361666f692e
Revises: 695d6a3b8fe9
Create Date: 2022-04-19 06:51:21.796243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b361666f692e'
down_revision = '695d6a3b8fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff-unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizationUnitId', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('positionId', sa.Integer(), nullable=True),
    sa.Column('typeId', sa.Integer(), nullable=True),
    sa.Column('staffCategoryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['positionId'], ['position.id'], ),
    sa.ForeignKeyConstraint(['staffCategoryId'], ['staff-category.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['staff-unit-type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff-unit_id'), 'staff-unit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff-unit_id'), table_name='staff-unit')
    op.drop_table('staff-unit')
    # ### end Alembic commands ###
