"""Edit all 2.0

Revision ID: ca7a220897e9
Revises: 115558b96141
Create Date: 2022-04-21 06:49:36.490760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7a220897e9'
down_revision = '115558b96141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_status_id'), 'employee_status', ['id'], unique=False)
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gender_id'), 'gender', ['id'], unique=False)
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_id'), 'grade', ['id'], unique=False)
    op.create_table('ldap_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ldap_login_id'), 'ldap_login', ['id'], unique=False)
    op.create_table('military_service_attitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_military_service_attitude_id'), 'military_service_attitude', ['id'], unique=False)
    op.create_table('nationality_sap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality_sap_id'), 'nationality_sap', ['id'], unique=False)
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eGovPositionId', sa.Integer(), nullable=True),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('declinationId', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_id'), 'position', ['id'], unique=False)
    op.create_table('replacement_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replacement_type_id'), 'replacement_type', ['id'], unique=False)
    op.create_table('staff_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_category_id'), 'staff_category', ['id'], unique=False)
    op.create_table('staff_unit_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employeeFuncRoleSpecId', sa.Integer(), nullable=True),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_unit_role_id'), 'staff_unit_role', ['id'], unique=False)
    op.create_table('staff_unit_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_unit_type_id'), 'staff_unit_type', ['id'], unique=False)
    op.create_table('marital_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('genderId', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genderId'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marital_status_id'), 'marital_status', ['id'], unique=False)
    op.create_table('nationality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('nationalitySAPId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nationalitySAPId'], ['nationality_sap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality_id'), 'nationality', ['id'], unique=False)
    op.create_table('staff_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizationUnitId', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('positionId', sa.Integer(), nullable=True),
    sa.Column('typeId', sa.Integer(), nullable=True),
    sa.Column('staffCategoryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['positionId'], ['position.id'], ),
    sa.ForeignKeyConstraint(['staffCategoryId'], ['staff_category.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['staff_unit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_unit_id'), 'staff_unit', ['id'], unique=False)
    op.create_table('nationality_gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('nationalityId', sa.Integer(), nullable=True),
    sa.Column('genderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genderId'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['nationalityId'], ['nationality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality_gender_id'), 'nationality_gender', ['id'], unique=False)
    op.create_table('internal_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individualId', sa.Integer(), nullable=True),
    sa.Column('legalOrganizationlId', sa.Integer(), nullable=True),
    sa.Column('fullnameDeclinationId', sa.Integer(), nullable=True),
    sa.Column('financialAccountId', sa.Integer(), nullable=True),
    sa.Column('iin', sa.String(), nullable=True),
    sa.Column('personnelNumber', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('middleName', sa.String(), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('workStartDate', sa.Date(), nullable=True),
    sa.Column('isReserveMember', sa.Boolean(), nullable=True),
    sa.Column('isInsider', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('statusId', sa.Integer(), nullable=True),
    sa.Column('gradeId', sa.Integer(), nullable=True),
    sa.Column('maritalStatusId', sa.Integer(), nullable=True),
    sa.Column('militaryServiceAttitudeId', sa.Integer(), nullable=True),
    sa.Column('nationalityGenderId', sa.Integer(), nullable=True),
    sa.Column('ldapLoginId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gradeId'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['ldapLoginId'], ['ldap_login.id'], ),
    sa.ForeignKeyConstraint(['maritalStatusId'], ['marital_status.id'], ),
    sa.ForeignKeyConstraint(['militaryServiceAttitudeId'], ['military_service_attitude.id'], ),
    sa.ForeignKeyConstraint(['nationalityGenderId'], ['nationality_gender.id'], ),
    sa.ForeignKeyConstraint(['statusId'], ['employee_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_employee_id'), 'internal_employee', ['id'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decreeId', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('isFRP', sa.Boolean(), nullable=True),
    sa.Column('isTemporary', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('employeeId', sa.Integer(), nullable=True),
    sa.Column('staffUnitId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['internal_employee.id'], ),
    sa.ForeignKeyConstraint(['staffUnitId'], ['staff_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_id'), 'appointment', ['id'], unique=False)
    op.create_table('replacement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('typeId', sa.Integer(), nullable=True),
    sa.Column('replacedId', sa.Integer(), nullable=True),
    sa.Column('replacerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['replacedId'], ['internal_employee.id'], ),
    sa.ForeignKeyConstraint(['replacerId'], ['internal_employee.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['replacement_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replacement_id'), 'replacement', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replacement_id'), table_name='replacement')
    op.drop_table('replacement')
    op.drop_index(op.f('ix_appointment_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_internal_employee_id'), table_name='internal_employee')
    op.drop_table('internal_employee')
    op.drop_index(op.f('ix_nationality_gender_id'), table_name='nationality_gender')
    op.drop_table('nationality_gender')
    op.drop_index(op.f('ix_staff_unit_id'), table_name='staff_unit')
    op.drop_table('staff_unit')
    op.drop_index(op.f('ix_nationality_id'), table_name='nationality')
    op.drop_table('nationality')
    op.drop_index(op.f('ix_marital_status_id'), table_name='marital_status')
    op.drop_table('marital_status')
    op.drop_index(op.f('ix_staff_unit_type_id'), table_name='staff_unit_type')
    op.drop_table('staff_unit_type')
    op.drop_index(op.f('ix_staff_unit_role_id'), table_name='staff_unit_role')
    op.drop_table('staff_unit_role')
    op.drop_index(op.f('ix_staff_category_id'), table_name='staff_category')
    op.drop_table('staff_category')
    op.drop_index(op.f('ix_replacement_type_id'), table_name='replacement_type')
    op.drop_table('replacement_type')
    op.drop_index(op.f('ix_position_id'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_nationality_sap_id'), table_name='nationality_sap')
    op.drop_table('nationality_sap')
    op.drop_index(op.f('ix_military_service_attitude_id'), table_name='military_service_attitude')
    op.drop_table('military_service_attitude')
    op.drop_index(op.f('ix_ldap_login_id'), table_name='ldap_login')
    op.drop_table('ldap_login')
    op.drop_index(op.f('ix_grade_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_gender_id'), table_name='gender')
    op.drop_table('gender')
    op.drop_index(op.f('ix_employee_status_id'), table_name='employee_status')
    op.drop_table('employee_status')
    # ### end Alembic commands ###
