"""Add replacement type

Revision ID: cda7589945b4
Revises: 295561489842
Create Date: 2022-04-18 09:43:18.678696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda7589945b4'
down_revision = '295561489842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replacement-type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replacement-type_id'), 'replacement-type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replacement-type_id'), table_name='replacement-type')
    op.drop_table('replacement-type')
    # ### end Alembic commands ###
