"""Add internal employee

Revision ID: dc4a859a5201
Revises: a540d5b9b71b
Create Date: 2022-04-19 08:21:49.015077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4a859a5201'
down_revision = 'a540d5b9b71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal-employee', sa.Column('isActive', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal-employee', 'isActive')
    # ### end Alembic commands ###
