"""Add staff category

Revision ID: ebaabd3e47ef
Revises: 888e7fb40601
Create Date: 2022-04-18 10:01:55.392831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebaabd3e47ef'
down_revision = '888e7fb40601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff-category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff-category_id'), 'staff-category', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff-category_id'), table_name='staff-category')
    op.drop_table('staff-category')
    # ### end Alembic commands ###
